name: remote ssh command
on:
    - pull_request
jobs:

  whoami:
    name: whoami and kernel
    runs-on: ubuntu-latest
    steps:
    - name: ssh to remote and check machine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.rpi_host }}
        username: ${{ secrets.rpi_username }}
        key: ${{ secrets.rpi_priv_key }}
        passphrase: ${{ secrets.rpi_passphrase }}
        port: ${{ secrets.rpi_port }}
        script: whoami && uname -a
